### ISSUE TITLE
nothing is displayed for a service-account

### ISSUE THREAD

**Issue by rgl** [corneliusweig/rakkess#35]
**Expected behavior**
the example-go-info service account is defined at https://github.com/rgl/rancher-single-node-ubuntu-vagrant/blob/da6c6030b5d4def7542b22b8fa8d368c4cad38be/examples/go-info/deployment.yml as:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-go-info
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-read
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-go-info-pod-read
subjects:
  - kind: ServiceAccount
    name: example-go-info
roleRef:
  kind: Role
  name: pod-read
  apiGroup: rbac.authorization.k8s.io
```

**Actual behavior**

The command returns nothing:

```
$ kubectl access-matrix --sa example-go-info --namespace default
NAME  LIST  CREATE  UPDATE  DELETE
```

**Steps To Reproduce**
1. kubectl apply the above manifest and try to get the service account access-matrix 

**Context:**

```
# kubectl access-matrix version --full
rakkess:    v0.4.1
platform:   linux/amd64
git commit: 946f6e2126cb584957eb0ad8cc0342fda7b8a1c9
build date: 2019-07-01T23:25:45Z
go version: go1.12.5
compiler:   gc
```
